{
  "extra": {
    "drop_file": false,
    "score": 0,
    "sections": [
      {
        "auto_collapse": false,
        "body": "Error using normal pycdc:\nCreateObject: Got unsupported type 0x27\nError loading file /tmp/d26b8d0e1000b81fee4c2ca4adcd8b0d3b19e7bfa5682f7bb6ea5ece72b249a0: std::bad_cast\n",
        "body_config": {},
        "body_format": "TEXT",
        "classification": "TLP:C",
        "depth": 0,
        "heuristic": null,
        "promote_to": null,
        "tags": {},
        "title_text": "Fallback to patched pycdc",
        "zeroize_on_tag_safe": false
      },
      {
        "auto_collapse": false,
        "body": "UnknownFilename.py",
        "body_config": {},
        "body_format": "TEXT",
        "classification": "TLP:C",
        "depth": 0,
        "heuristic": null,
        "promote_to": null,
        "tags": {},
        "title_text": "Successfully extracted 1 file that was safelisted.",
        "zeroize_on_tag_safe": false
      }
    ]
  },
  "files": {
    "extracted": [],
    "supplementary": []
  },
  "results": {
    "heuristics": [],
    "tags": {},
    "temp_submission_data": {}
  }
}